### PR TITLE
Update manifest.json

### PR DESCRIPTION
**Pull request by Selawen**
I changed the colour to the TU colour 
(issue #43 )

### CODE REVIEW

**Comment by RobbinBaauw** [comment]
Sure but this is only part of the issue:joy:

**Comment by RobbinBaauw** [comment]
Closing this one as it's a very empty PR

**Comment by NULLx76** [comment]
It does partly fix the issue though, right?

**Comment by Selawen** [comment]
What did you want to change then?

**Comment by RobbinBaauw** [comment]
Yes but there is more to do, let's do a PR with all of this fixed (and if you pick up an issue, @Selawen, please do the entire one, as changing one string is 0 effort for us as well, we could do that when doing this issue anyway:smile:)

**Comment by Selawen** [comment]
I understand what went wrong now, I didn't realise there were 3 different issues packed into 1

**Comment by RobbinBaauw** [comment]
Ah okay great, no offense of course, just want to have everything in 1 place, and I don't like too many commits (though right now there are way too many in the master as well imo)

**Comment by NULLx76** [comment]
The best practice is actually to commit often. We can always squash commits later if we would want to.

[Reference: Git Best Practices](https://sethrobertson.github.io/GitBestPractices/)

**Comment by RobbinBaauw** [comment]
Yes, but I disagree with committing such a small change, which doesn't need any kind of checkpoint or something (which is why you would commit often). Then we have by far the easiest and smallest part of 1 issue solved. So I'd reckon that if a contributor wants to do a PR, they should have fixed the entire issue, so we don't merge 1/3rd of the issue

**Pull request merged**
